### ISSUE TITLE
Implement scoped storage as necessary for import/export

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.inventory#254]
Based on https://www.youtube.com/watch?v=jcO6p5TlcGs&list=PLWz5rJ2EKKc8PO99T1QQLrPAJILqxJXW6&index=10 this needs a full re-think.

https://youtu.be/jcO6p5TlcGs?t=492 to the rescue, but this library needs a lot of AndroidX bumps:
https://developer.android.com/jetpack/androidx/releases/activity

TODOs: main ticket is #270 and #278, rest is cleanup

- [x] Aim: make import/export work again
  - [x] Rewrite BackupActivity's import/export (#270)
- [x] Aim: remove `requestLegacyExternalStorage`, see also `todo/fix254_storage` branch.
  - [x] Done in #270, but review still
- [x] Aim: review `ScopedStorage` and `*_EXTERNAL_STORAGE` permission usages.
  - [x] Done in #270, but review still
- [x] Aim: remove `Paths.getPhoneHome` and `Paths.getExportFile`
  - [x] Rewrite ManageSpace to use the same facilities
      - [x] #268
      - [x] #278
      - [x] #279
  - [x] Rewrite export categories debug util to use the same facilities (#267)
- [x] Aim: remove net.twisterrob.android.utils.tools.AndroidTools#makeFileDiscoverable usages
  - [x] Rewrite export categories debug page to use the same facilities (#267)
- [x] Aim: better UX
  - [x] Error handling propagation to UI
  - [x] Custom message when inventory XML is missing or invalid (#267)
- [x] Aim: Reduce ways of importing
  - [x] delete BackupZipFileImporter?
